# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: adfad9c26d1e85e6a0c6994abcc2d5fdb2c7835a4012c5f8fab3833e5670e327862c0e68b485c17e96139ab5c3d34a95828dcf889a4d4374e14d34345297ff19

test:
  secret_key_base: b63295e704e527ab9ac97c7092c8ae863deae84ff59d775db1dcb62ed63a012b4e7e10fd4195736ecefdc82749fe7628aff091192847116b2e2a7b91b1bb7cc3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
